spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: test-route
        uri: lb://SAMPLE-ENDPOINT
        predicates:
        - Path=/test/**
        filters:
        - StripPrefix=1